config/routes.rb
Rails.application.routes.draw do
resources :characters
resources :transformations, only: [:index, :show, :new, :edit, :create, :update]
resources :character_transformations, only: [:index, :show, :new, :create]
get '/', to: 'application#home', as: 'home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def home
    
  end
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/character_transformation.rb
class CharacterTransformation < ApplicationRecord
    belongs_to :character
    belongs_to :transformation

    def self.index(id)
        CharacterTransformation.where :character_id => id
      end

end

app/models/transformation.rb
class Transformation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/character_transformations_controller.rb
class CharacterTransformationsController < ApplicationController


  # def show
  #   @ct = CharacterTransformation.find(params[:id])
  # end

  def new
    @ct = CharacterTransformation.new 
  end

  def create 
    @ct = CharacterTransformation.create(ct_params)
    redirect_to character_transformation_path(@ct)

  end

  private

  def ct_params
    params.require(:character_transformation).permit(:name, :character_id, :transformation_id)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
    @transformations = CharacterTransformation.index(params[:id]) 
    
  end

  def new
    @character = Character.new
  end

  def create 
    @character = Character.create(character_params)
    @transformation = Transformation.find(transformation_params[:transformation_id].to_i)
    @ct = CharacterTransformation.create(
      name: "#{@character.name}, #{@transformation.name}",
      character_id: @character.id, 
      transformation_id: @transformation.id)
    redirect_to character_path(@character)
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    @character.update(character_params(:name, :power_level))
  end

  private

  def character_params
    params.require(:character).permit(:name, :race, :series, :power_level)
  end

  def transformation_params
    params.require(:transformation).permit(:name, :transformation_id)
  end
end

app/controllers/transformations_controller.rb
class TransformationsController < ApplicationController
  def index
    @transformations = Transformation.all
  end

  def show
    @transformation = Transformation.find(params[:id])
  end

  def new
    @transformation = Transformation.new
  end

  def create
    @transformation = Transformation.create(transformation_params)
    redirect_to transformation_path(@transformation)
  end

  private

  def transformation_params
    params.require(:transformation).permit(:name, :required_transformations)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/charactertransformations_helper.rb
module CharactertransformationsHelper
end

app/helpers/transformations_helper.rb
module TransformationsHelper
end

app/views/application/home.html.erb
<h1>Scouter Readings</h1>
<%= link_to 'Characters', characters_path %><br>
<%= link_to 'Transformations', transformations_path %><br>

app/views/character_transformations/edit.html.erb
<h1>Charactertransformations#edit</h1>
<p>Find me in app/views/charactertransformations/edit.html.erb</p>

app/views/character_transformations/index.html.erb
<h1>Character Transformations</h1>
<p>Find me in app/views/charactertransformations/index.html.erb</p>

app/views/character_transformations/new.html.erb
<h1>Charactertransformations#new</h1>
<p>Find me in app/views/charactertransformations/new.html.erb</p>

app/views/character_transformations/show.html.erb
<h1>Charactertransformations#show</h1>
<p>Find me in app/views/charactertransformations/show.html.erb</p>

app/views/characters/edit.html.erb
<h1>Edit Character</h1>
<%= form_for @character do |f| %><br>
<%= f.label :name%><br>
<%= f.text_field :name %><br>
<%= f.label :power_level%><br>
<%= f.number_field :power_level %><br>
<%= f.submit %><br>
<% end %><br>

app/views/characters/index.html.erb
<h1>Characters</h1>
<h2><ul>
<% @characters.each do |c|%>
<li><%= link_to c.name, character_path(c) %></li>
<%end%>
</ul></h2>
<div><h2> 
<%= link_to 'Add New Character', new_character_path %><br>
<%= link_to 'Home', home_path %>

app/views/characters/new.html.erb
<h1>Add Character</h1>
<%= form_for @character do |f| %>
<%= f.label 'Name:'%><br>
<%= f.text_field :name %><br>
<%= f.label 'Race:'%><br>
<%= f.text_field :race %><br>
<%= f.label 'Series'%><br>
<%= f.text_field :series %><br>
<%= f.label 'Power Level'%><br>
<%= f.number_field :power_level %><br>
<%= collection_select(:transformation, :transformation_id, Transformation.all, :id, :name)%>
<%= f.submit 'Submit'%>
<%end%>
<%= link_to "<--Back", characters_path %>

app/views/characters/show.html.erb
<h1>Character Details</h1>
<h2>Name: <%= @character.name %></h2>
<h3>Series: <%= @character.series %></h3>
<h3>Race: <%= @character.race %></h3>
<h3>Power Level: <%= @character.power_level %></h3>
<h2>Transformations:</h2>
<ul>
 <%@transformations.each do |c| %>
 <li><%= c.name %></li>
 <%end%>
 </ul><br>
<%= link_to "Edit", edit_character_path(@character) %><br><br>

<%= link_to "<--Back", characters_path %>

app/views/charactertransformations/index.html.erb
<h1>Charactertransformations#index</h1>
<p>Find me in app/views/charactertransformations/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DragonBallTransformations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transformations/edit.html.erb
<h1>Transformations#edit</h1>
<p>Find me in app/views/transformations/edit.html.erb</p>

app/views/transformations/index.html.erb
<h1>Transformations</h1>
<ul>
<% @transformations.each do |t| %>
<li><%= link_to t.name, transformation_path(t) %></li>
<% end %>
</ul>
<%= link_to "New Transformation", new_transformation_path %><br><br>
<%= link_to 'Home', home_path %>

app/views/transformations/new.html.erb
<h1>Ascend To The Next Transformation</h1>
<%= form_for @transformation do |f| %><br>
<%= f.label :name %>:<br>
<%= f.text_field :name %><br>
<%= f.label :required_transformations %>:<br>
<%= f.text_field :required_transformations %><br>
<%= f.submit %><br>
<% end %>
<%= link_to "<--Back", transformations_path %>

app/views/transformations/show.html.erb
<h1>Transformation Details</h1>
<h2>Name: <%= @transformation.name %></h2>
<h2>Required Transformations: <%= @transformation.required_transformations %></h2><br>
<%= link_to "<--Back", transformations_path %>